apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowable-ui
  template:
    metadata:
      labels:
        app: flowable-ui
    spec:
      containers:
        - name: flowable-ui
          image: flowable/flowable-ui:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: flowable-ui-config
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 600Mi
              cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flowable-ui
spec:
  type: NodePort
  selector:
    app: flowable-ui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-ui-config
data:
  FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
  FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test